# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := WarsawTimeConverterTest
ARDUINO_LIBS := AUnit Timezone Time
ARDUINO_LIB_DIRS := ${HOME}/Arduino/libraries
include ../../libraries/EpoxyDuino/EpoxyDuino.mk
