# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := computeFakeTimeTest
ARDUINO_LIBS := AUnit
ARDUINO_LIB_DIRS := ${ARDUINO_CLI_DIR}/libraries
include ../../libraries/EpoxyDuino/EpoxyDuino.mk
