# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := FakeTimeTest
ARDUINO_LIBS := AUnit ../../main/Faketime
ARDUINO_LIB_DIRS := ${ARDUINO_CLI_DIR}/libraries ../../main
include ../../libraries/EpoxyDuino/EpoxyDuino.mk
