name: clang-format Check
on:
  - push
  - pull_request

jobs:
  # https://github.com/marketplace/actions/clang-format-check#single-path
  formatting-check:

    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '13'
        check-path: 'src'
