name: Continuous Integration

on:
  - pull_request

env:
  # https://arduino.github.io/arduino-cli/latest/installation/#download
  ARDUINO_CLI_FILE: arduino-cli_latest_Linux_64bit.tar.gz
  # for https://github.com/bxparks/EpoxyDuino#additional-arduino-library-locations
  ARDUINO_CLI_DIR: ${HOME}/Arduino

jobs:
  # https://github.com/marketplace/actions/clang-format-check#single-path
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '13'
        check-path: 'crazyclock'

  tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Download Arduino cli
        run: |
          wget https://downloads.arduino.cc/arduino-cli/${ARDUINO_CLI_FILE}
          tar -zxf ${ARDUINO_CLI_FILE}
          rm -fr ${ARDUINO_CLI_FILE}

      - name: Init Arduino cli config
        run: ./arduino-cli config init --overwrite

      - name: Install esp8266
        run: |
          ./arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          ./arduino-cli core update-index
          ./arduino-cli core install esp8266:esp8266

      - name: Install Libraries Required by Unit Tests
        run: ./arduino-cli lib install AUnit Time Timezone

      - name: List top directory
        run: ls -lah

      - name: List libraries
        run: ls -lah $HOME/Arduino/libraries

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: crazyclock

      - name: Checkout EpoxyDuino
        uses: actions/checkout@v3
        with:
          repository: bxparks/EpoxyDuino
          ref: v1.3.0
          path: crazyclock/libraries/EpoxyDuino

      - name: Compile tests
        run: make -C crazyclock/src/ make_all

      - name: Run tests
        run: make -C crazyclock/src/ runtests

  compile:
    name: Compile for Wemos D1
    runs-on: ubuntu-20.04
    steps:
      - name: Download Arduino cli
        run: |
          wget https://downloads.arduino.cc/arduino-cli/${ARDUINO_CLI_FILE}
          tar -zxf ${ARDUINO_CLI_FILE}
          rm -fr ${ARDUINO_CLI_FILE}

      - name: Init Arduino cli config
        run: ./arduino-cli config init --overwrite

      - name: Install esp8266
        run: |
          ./arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          ./arduino-cli core update-index
          ./arduino-cli core install esp8266:esp8266

      - name: Install Libraries Required by Sketch
        run: ./arduino-cli lib install "hd44780" "NTPClient" "RotaryEncoder"

      - name: List top directory
        run: ls -lah

      - name: List libraries
        run: ls -lah $HOME/Arduino/libraries

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: crazyclock

      - name: Compile Sketch for Wemos D1
        run: ./arduino-cli --verbose compile --fqbn esp8266:esp8266:d1 crazyclock/crazyclock/
