# https://github.com/marketplace/actions/bazel-action
name: Unit tests with Bazel
on: push
jobs:
  checks:
    name: run-unit-tests 
    runs-on: ubuntu-latest

    steps:
    - name: Get source
      uses: actions/checkout@master
    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //:hello_test
