# https://github.com/marketplace/actions/bazel-action
name: Unit tests with Bazel

on: push

jobs:

  checks:
    name: run
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: run
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        entryPoint: src/hello
        args: test //:hello_test
