name: Unit tests with EpoxyDuino
on:
  - push
  - pull_request

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: crazyclock

      - name: Checkout EpoxyDuino
        uses: actions/checkout@v3
        with:
          repository: bxparks/EpoxyDuino
          ref: v1.3.0
          path: EpoxyDuino

      - name: Download Arduino cli
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_0.21.1_Linux_64bit.tar.gz
          tar -zxf arduino-cli_0.21.1_Linux_64bit.tar.gz
          ./arduino-cli config init
          ./arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          ./arduino-cli core update-index
          ./arduino-cli core install esp8266:esp8266

      - name: List Dir
        run: ls -lah

      - name: Compile tests
        run: cd crazyclock/src && make -C test

      - name: Run tests
        run: cd src && make -C test runtests
