name: Unit tests with EpoxyDuino
on:
  - push
  - pull_request

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: crazyclock

      - name: Checkout EpoxyDuino
        uses: actions/checkout@v3
        with:
          repository: bxparks/EpoxyDuino
          ref: v1.3.0
          path: EpoxyDuino

      - name: List Dir
        run: ls -lah

      - name: Disk Usage
        run: du -h -d2

      - name: Compile tests
        run: cd crazyclock/src && make -C test

      - name: Run tests
        run: cd src && make -C test runtests
